version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: shop_add_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop-add
      MYSQL_USER: shop-add
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shop_add_network

volumes:
  mysql_data:

networks:
  shop_add_network:
    driver: bridge
